package view;

import controller.*;
import controller.PolicialPenalController;
import controller.VisitasController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import model.PolicialPenalModel;
import model.VisitasModel;
import util.Relatorios;

/**
 *
 * @author felip
 */
public class IPLView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PolicialPenalView
     */
    private int linha = -1; // USADO PARA VERIFICAR SE ALGUMA LINHA DA TABELA FOI SELECIONADA

    private ArrayList<CrimesModel> listaCrimes;
    private ArrayList<VisitasModel> listaVisitantes;
    private ArrayList<RefeicaoModel> listaRefeicao;
    private ArrayList<PolicialPenalModel> listaPolicial;

    public IPLView() {
        initComponents();
        inicializar();
        preencherTabela();
        preencherComboBoxCrimes();
        preencherComboBoxParentesco();
        preencherComboBoxRefeicao();
        preencherComboBoxPolicial();
    }

    private void inicializar() {
        cxt_id.setEnabled(false);
        cxt_cpf.setEnabled(false);
        cxt_nome.setEnabled(false);
        cxt_crime.setEnabled(false);
        cxt_parentesco.setEnabled(false);
        cxt_refeicao.setEnabled(false);
        cxt_policial.setEnabled(false);

        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
        btn_novo.setEnabled(true);

    }

    private void preencherTabela() {
        IPLController controller = new IPLController();
        ArrayList<IPLModel> lista = controller.selecionarTodos();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NENHUM IPL CADASTRADO! (IPLView ln 41)",
                    "Preenchendo tabela....", JOptionPane.INFORMATION_MESSAGE);

        } else {
            DefaultTableModel modeloTabela = (DefaultTableModel) tb_ipl.getModel();
            modeloTabela.setRowCount(0);
            for (IPLModel i : lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(i.getIdipl()),
                    i.getIpl_cpf(),
                    i.getIpl_nome(),
                    i.getCrime().getDescricao(),
                    i.getParentesco().getParentesco(),
                    i.getRefeicao().getComida(),
                    i.getPolicial().getNome()
                });
            }
        }
    }

    private void limparCampos() {
        cxt_id.setText("");
        cxt_cpf.setText("");
        cxt_nome.setText("");
        cxt_crime.setSelectedItem("");
        cxt_parentesco.setSelectedItem("");
        cxt_refeicao.setSelectedItem("");
        cxt_policial.setSelectedItem("");
    }

    private void preencherComboBoxCrimes() {
        CrimesController controller = new CrimesController();
        listaCrimes = controller.selecionarTodos();
        for (CrimesModel x : listaCrimes) {
            cxt_crime.addItem(x.getDescricao());
        }
    }

    private void preencherComboBoxParentesco() {
        VisitasController controller = new VisitasController();
        listaVisitantes = controller.selecionarTodos();
        for (VisitasModel v : listaVisitantes) {
            cxt_parentesco.addItem(v.getParentesco());
        }
    }

    private void preencherComboBoxRefeicao() {
        RefeicaoController controller = new RefeicaoController();
        listaRefeicao = controller.selecionarTodos();
        for (RefeicaoModel v : listaRefeicao) {
            cxt_refeicao.addItem(v.getComida());
        }
    }

    private void preencherComboBoxPolicial() {
        PolicialPenalController controller = new PolicialPenalController();
        listaPolicial = controller.selecionarTodos();
        for (PolicialPenalModel v : listaPolicial) {
            cxt_policial.addItem(v.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cxt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxt_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cxt_cpf = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ipl = new javax.swing.JTable();
        btn_excluir = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cxt_crime = new javax.swing.JComboBox<>();
        cxt_parentesco = new javax.swing.JComboBox<>();
        cxt_refeicao = new javax.swing.JComboBox<>();
        cxt_policial = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Tela Indivíduo Privado de Liberdade");
        setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        jLabel1.setText("Nome Indivíduo:");

        cxt_nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setText("CPF:");

        jLabel3.setText("Crime:");

        jLabel4.setText("Parentesco:");

        cxt_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_idActionPerformed(evt);
            }
        });

        jLabel5.setText("Id:");

        try {
            cxt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxt_cpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tb_ipl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "NOME", "CRIME", "CONTATO", "REFEIÇÃO", "POLICÍAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_ipl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_iplMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_ipl);
        if (tb_ipl.getColumnModel().getColumnCount() > 0) {
            tb_ipl.getColumnModel().getColumn(0).setResizable(false);
            tb_ipl.getColumnModel().getColumn(1).setResizable(false);
            tb_ipl.getColumnModel().getColumn(2).setResizable(false);
            tb_ipl.getColumnModel().getColumn(3).setResizable(false);
            tb_ipl.getColumnModel().getColumn(4).setResizable(false);
            tb_ipl.getColumnModel().getColumn(5).setResizable(false);
            tb_ipl.getColumnModel().getColumn(6).setResizable(false);
        }

        btn_excluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_novoMouseClicked(evt);
            }
        });
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        jLabel6.setText("Refeição:");

        jLabel7.setText("Policíal vinculado:");

        cxt_crime.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_parentesco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_refeicao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_policial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_novo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excluir)
                                .addGap(0, 375, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxt_refeicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxt_crime, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxt_parentesco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cxt_policial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_fechar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_imprimir, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_fechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cxt_crime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cxt_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cxt_policial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cxt_refeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_editar)
                    .addComponent(btn_novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_imprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_novoMouseClicked

    private void cxt_idActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cxt_idActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cxt_idActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_excluirActionPerformed
        if (cxt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ESCOLHA UMA LINHA PARA EXCLUIR!", "Excluindo....",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {

            // ---------------- CONTROLLER
            PolicialPenalController controller = new PolicialPenalController();
            if (controller.editar(Integer.parseInt(cxt_id.getText()))) {
                JOptionPane.showMessageDialog(this, "Dados excluídos", "excluindo...!",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EXCLUIR POLICIALPENAL",
                        "Algo de errado não está certo....", JOptionPane.ERROR_MESSAGE);

            }
        }
    }

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_novoActionPerformed

        cxt_id.setEnabled(false);
        cxt_cpf.setEnabled(true);
        cxt_nome.setEnabled(true);
        cxt_crime.setEnabled(true);
        cxt_parentesco.setEnabled(true);
        cxt_refeicao.setEnabled(true);
        cxt_policial.setEnabled(true);

        btn_novo.setEnabled(false);
        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);

        limparCampos();
        cxt_nome.requestFocus();

    }

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_salvarActionPerformed

    }

    private void acaoGerarRelatorio() throws IOException {

        Relatorios.relatorio("relatorio_ipl", "", "");

    }

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_imprimirActionPerformed

        try {
            acaoGerarRelatorio();
        } catch (IOException ex) {
            Logger.getLogger(IPLView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void tb_iplMouseClicked(java.awt.event.MouseEvent evt) {
        linha = tb_ipl.getSelectedRow();

        if (linha != -1) {
            cxt_id.setText(tb_ipl.getValueAt(linha, 0).toString());
            cxt_cpf.setText(tb_ipl.getValueAt(linha, 1).toString());
            cxt_nome.setText(tb_ipl.getValueAt(linha, 2).toString());
            cxt_crime.setSelectedItem(tb_ipl.getValueAt(linha, 3).toString());
            cxt_parentesco.setSelectedItem(tb_ipl.getValueAt(linha, 4).toString());
            cxt_refeicao.setSelectedItem(tb_ipl.getValueAt(linha, 5).toString());
            cxt_policial.setSelectedItem(tb_ipl.getValueAt(linha, 6).toString());

            btn_novo.setEnabled(false);
            btn_salvar.setEnabled(false);
            btn_editar.setEnabled(true);
            btn_excluir.setEnabled(true);

            cxt_id.setEnabled(false);
            cxt_cpf.setEnabled(true);
            cxt_nome.setEnabled(true);
            cxt_crime.setEnabled(true);
            cxt_parentesco.setEnabled(true);
            cxt_refeicao.setEnabled(true);
            cxt_policial.setEnabled(true);

            linha = -1;

        }
    }

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {

        int id = Integer.parseInt(cxt_id.getText());
        String nome = cxt_nome.getText();
        String cpf = cxt_cpf.getText();
        String crime = cxt_crime.getSelectedItem().toString();
        String parentesco = cxt_parentesco.getSelectedItem().toString();
        String refeicao = cxt_refeicao.getSelectedItem().toString();
        String policial = cxt_policial.getSelectedItem().toString();

        if (nome.isEmpty() || cpf.isEmpty() || crime.isEmpty() || parentesco.isEmpty() || refeicao.isEmpty() || policial.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe todos os campos.....", "Atenção!",
                    JOptionPane.WARNING_MESSAGE);

        } else {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JFormattedTextField cxt_cpf;
    private javax.swing.JComboBox<String> cxt_crime;
    private javax.swing.JTextField cxt_id;
    private javax.swing.JTextField cxt_nome;
    private javax.swing.JComboBox<String> cxt_parentesco;
    private javax.swing.JComboBox<String> cxt_policial;
    private javax.swing.JComboBox<String> cxt_refeicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb_ipl;
    // End of variables declaration//GEN-END:variables
}
