/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author felip
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/tropaDeElite.jpg"));
        Image image = icon.getImage();
        panel_areaDeTrabalho = new javax.swing.JDesktopPane() {

            public void paintComponent(Graphics g) {
                g.drawImage(image, 0,0,getWidth(), getHeight(), this);
            }

        };
        menu_barra = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_ipl = new javax.swing.JMenuItem();
        menuItem_policialPenal = new javax.swing.JMenuItem();
        menuItem_celas = new javax.swing.JMenuItem();
        menuItem_crimes = new javax.swing.JMenuItem();
        menuItem_visitas = new javax.swing.JMenuItem();
        menuItem_refeicoes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel_areaDeTrabalhoLayout = new javax.swing.GroupLayout(panel_areaDeTrabalho);
        panel_areaDeTrabalho.setLayout(panel_areaDeTrabalhoLayout);
        panel_areaDeTrabalhoLayout.setHorizontalGroup(
            panel_areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );
        panel_areaDeTrabalhoLayout.setVerticalGroup(
            panel_areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        menuItem_ipl.setText("Indivíduo Privado de Liberdade ");
        jMenu1.add(menuItem_ipl);

        menuItem_policialPenal.setText("Políciais Penais");
        jMenu1.add(menuItem_policialPenal);

        menuItem_celas.setText("Celas");
        jMenu1.add(menuItem_celas);

        menuItem_crimes.setText("Crimes");
        jMenu1.add(menuItem_crimes);

        menuItem_visitas.setText("Visitas");
        jMenu1.add(menuItem_visitas);

        menuItem_refeicoes.setText("Refeições");
        jMenu1.add(menuItem_refeicoes);

        menu_barra.add(jMenu1);
        menu_barra.add(jMenu2);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_areaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_areaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem menuItem_celas;
    private javax.swing.JMenuItem menuItem_crimes;
    private javax.swing.JMenuItem menuItem_ipl;
    private javax.swing.JMenuItem menuItem_policialPenal;
    private javax.swing.JMenuItem menuItem_refeicoes;
    private javax.swing.JMenuItem menuItem_visitas;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JDesktopPane panel_areaDeTrabalho;
    // End of variables declaration//GEN-END:variables
}
