package view;

import controller.IPLController;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.CrimesModel;
import model.IPLModel;
import model.PolicialPenalModel;
import model.RefeicaoModel;
import model.VisitasModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.Conexao;
import util.Relatorios;

/**
 *
 * @author felip
 */
public class PesquisaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaView
     */
    public PesquisaView() {
        initComponents();
        cxt_nome.setEnabled(false);
        cxt_crime.setEnabled(false);
        cxt_policial.setEnabled(false);

        cxt_cpf.requestFocus();
    }

    private ArrayList<CrimesModel> listaCrimes;
    private ArrayList<VisitasModel> listaVisitantes;
    private ArrayList<RefeicaoModel> listaRefeicao;
    private ArrayList<PolicialPenalModel> listaPolicial;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_fechar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        cxt_cpf = new javax.swing.JFormattedTextField();
        cxt_crime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cxt_nome = new javax.swing.JTextField();
        cxt_policial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Tela Busca e Retorno");

        jLabel1.setText("Informe CPF IPL:");

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        try {
            cxt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxt_cpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_crime.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_crime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_crimeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Indivíduo:");

        jLabel3.setText("Crime:");

        cxt_nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_nomeActionPerformed(evt);
            }
        });

        cxt_policial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_policial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_policialActionPerformed(evt);
            }
        });

        jLabel4.setText("Polícial Vinculado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_crime, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_policial)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscar)))
                                .addGap(0, 128, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_imprimir, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_fechar, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btn_fechar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxt_crime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxt_policial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_imprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void acaoGerarRelatorio() throws IOException {

        Conexao.conectar();

        try {

            Map<String, Object> parameters = new HashMap<>();
            parameters.put("buscaCpf", cxt_cpf.getText());

            JasperCompileManager.compileReportToFile("src\\relatorios\\" + "relatorio_buscaCpf" + ".jrxml");

            JasperPrint print = JasperFillManager.fillReport("src\\relatorios\\" + "relatorio_buscaCpf" + ".jasper", parameters, Conexao.conector);

            JasperViewer viewer = new JasperViewer(print, false);

            if (print.getPages().isEmpty()) {
                System.out.println("====================== Relatório está vazio (sem páginas).");
            } else {
                System.out.println("========================== Relatório gerado com sucesso. Total de páginas: " + print.getPages().size());
            }

            JasperExportManager.exportReportToPdfFile(print, "relatorio_buscaCpf" + ".pdf");

            String aleatorio = System.getProperty("java.io.tmpdir") + File.separator + "relatorio_" + System.currentTimeMillis() + ".pdf";
            JasperExportManager.exportReportToPdfFile(print, aleatorio);

            Desktop desktop = Desktop.getDesktop();
            File file = new File(aleatorio);
            desktop.open(file);

        } catch (JRException e) {
            throw new RuntimeException("ImpossÃ­vel abrir relatÃ³rio! ", e);
        } finally {
            if (Conexao.conector != null) {
                Conexao.desconectar();
            }

        }

        //Relatorios.relatorio("relatorio_buscaCpf", cxt_cpf.getText(), "");
    }


    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        try {
            acaoGerarRelatorio();

        } catch (IOException ex) {
            Logger.getLogger(IPLView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        String cpf = cxt_cpf.getText();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe todos os campos.....", "Atenção!",
                    JOptionPane.WARNING_MESSAGE);

        } else {

            // ---------------- CONTROLLER
            IPLController controller = new IPLController();
            IPLModel busca = controller.buscarCpf(cpf);
            if (busca != null) {

                cxt_nome.setText(busca.getIpl_nome());
                cxt_crime.setText(busca.getCrime().getDescricao());
                cxt_policial.setText(busca.getPolicial().getNome());

                JOptionPane.showMessageDialog(this, "Dados Encontrados", "Atualizando...!",
                        JOptionPane.INFORMATION_MESSAGE);

                busca = null;
                cpf = "";
                cxt_cpf.setEnabled(false);
                btn_buscar.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO BUSCAR CPF", "Algo de errado não está certo....",
                        JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_btn_buscarActionPerformed

    private void cxt_crimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxt_crimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxt_crimeActionPerformed

    private void cxt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxt_nomeActionPerformed

    private void cxt_policialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxt_policialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxt_policialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JFormattedTextField cxt_cpf;
    private javax.swing.JTextField cxt_crime;
    private javax.swing.JTextField cxt_nome;
    private javax.swing.JTextField cxt_policial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
