package view;

import controller.PolicialPenalController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PolicialPenalModel;
import util.Relatorios;

/**
 *
 * @author felip
 */
public class PolicialPenalView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PolicialPenalView
     */
    private int linha = -1; // USADO PARA VERIFICAR SE ALGUMA LINHA DA TABELA FOI SELECIONADA

    public PolicialPenalView() {
        initComponents();
        inicializar();
        preencherTabela();
    }

    private void inicializar() {
        cxt_id.setEnabled(false);
        cxt_cpf.setEnabled(false);
        cxt_nome.setEnabled(false);
        cxt_entrada.setEnabled(false);
        cxt_saida.setEnabled(false);

        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
        btn_novo.setEnabled(true);

    }

    private void preencherTabela() {
        PolicialPenalController controller = new PolicialPenalController();
        ArrayList<PolicialPenalModel> lista = controller.selecionarTodos();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NENHUM POLICIAL PENAL CADASTRADO! (PolicialPenalView ln 41)", "Preenchendo tabela....", JOptionPane.INFORMATION_MESSAGE);

        } else {
            DefaultTableModel modeloTabela = (DefaultTableModel) tb_policial.getModel();
            modeloTabela.setRowCount(0);
            for (PolicialPenalModel pp : lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(pp.getIdpolicialpenal()),
                    pp.getCpf(),
                    pp.getNome(),
                    pp.getTurno_entrada(),
                    pp.getTurno_saida()
                });
            }
        }
    }

    private void limparCampos() {
        cxt_id.setText("");
        cxt_cpf.setText("");
        cxt_nome.setText("");
        cxt_entrada.setText("");
        cxt_saida.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cxt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cxt_entrada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cxt_saida = new javax.swing.JTextField();
        cxt_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cxt_cpf = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_policial = new javax.swing.JTable();
        btn_excluir = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Tela Policial Penal");

        jLabel1.setText("Nome Polícial:");

        cxt_nome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setText("CPF:");

        jLabel3.setText("Turno Entrada:");

        cxt_entrada.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel4.setText("Turno Saída:");

        cxt_saida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_idActionPerformed(evt);
            }
        });

        jLabel5.setText("Id:");

        try {
            cxt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxt_cpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tb_policial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "NOME", "ENTRADA", "SAÍDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_policial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_policialMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_policial);
        if (tb_policial.getColumnModel().getColumnCount() > 0) {
            tb_policial.getColumnModel().getColumn(0).setResizable(false);
            tb_policial.getColumnModel().getColumn(1).setResizable(false);
            tb_policial.getColumnModel().getColumn(2).setResizable(false);
            tb_policial.getColumnModel().getColumn(3).setResizable(false);
            tb_policial.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_excluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_fechar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_entrada)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_imprimir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_fechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(cxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cxt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cxt_saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_editar)
                    .addComponent(btn_novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_imprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxt_idActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        if (cxt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ESCOLHA UMA LINHA PARA EXCLUIR!", "Excluindo....", JOptionPane.INFORMATION_MESSAGE);

        } else {

            //---------------- CONTROLLER
            PolicialPenalController controller = new PolicialPenalController();
            if (controller.editar(Integer.parseInt(cxt_id.getText()))) {
                JOptionPane.showMessageDialog(this, "Dados excluídos", "excluindo...!", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EXCLUIR POLICIALPENAL", "Algo de errado não está certo....", JOptionPane.ERROR_MESSAGE);

            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed

        cxt_id.setEnabled(false);
        cxt_cpf.setEnabled(true);
        cxt_nome.setEnabled(true);
        cxt_entrada.setEnabled(true);
        cxt_saida.setEnabled(true);

        btn_novo.setEnabled(false);
        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);

        limparCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        String cpf = cxt_cpf.getText();
        String nome = cxt_nome.getText();
        String entrada = cxt_entrada.getText();
        String saida = cxt_saida.getText();

        if (cpf.isEmpty() || nome.isEmpty() || entrada.isEmpty() || saida.isEmpty()) {
            JOptionPane.showMessageDialog(this, "INFORME TODOS OS CAMPOS!", "Atenção....", JOptionPane.WARNING_MESSAGE);

        } else {
            PolicialPenalModel policial = new PolicialPenalModel();
            policial.setCpf(cpf);
            policial.setNome(nome);
            policial.setTurno_entrada(entrada);
            policial.setTurno_saida(saida);

            //------------ CONTROLLER
            PolicialPenalController controller = new PolicialPenalController();
            if (controller.inserir(policial)) {
                JOptionPane.showMessageDialog(this, "POLICIAL CADASTRADO!", "Salvamento realizado...", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO INSERIR FORNECEDOR", "Algo de errado não está certo....", JOptionPane.ERROR_MESSAGE);

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed

        this.dispose();

    }//GEN-LAST:event_btn_fecharActionPerformed

    private void tb_policialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_policialMouseClicked
        linha = tb_policial.getSelectedRow();

        if (linha != -1) {
            cxt_id.setText(tb_policial.getValueAt(linha, 0).toString());
            cxt_cpf.setText(tb_policial.getValueAt(linha, 1).toString());
            cxt_nome.setText(tb_policial.getValueAt(linha, 2).toString());
            cxt_entrada.setText(tb_policial.getValueAt(linha, 3).toString());
            cxt_saida.setText(tb_policial.getValueAt(linha, 4).toString());

            btn_novo.setEnabled(false);
            btn_salvar.setEnabled(false);
            btn_editar.setEnabled(true);
            btn_excluir.setEnabled(true);

            cxt_id.setEnabled(false);
            cxt_cpf.setEnabled(true);
            cxt_nome.setEnabled(true);
            cxt_entrada.setEnabled(true);
            cxt_saida.setEnabled(true);
            linha = -1;

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_policialMouseClicked

    private void acaoGerarRelatorio() throws IOException {

        Relatorios.relatorio("relatorio_policialPenal", "", "");

    }

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed

        try {
            acaoGerarRelatorio();

            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(PolicialPenalView.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JFormattedTextField cxt_cpf;
    private javax.swing.JTextField cxt_entrada;
    private javax.swing.JTextField cxt_id;
    private javax.swing.JTextField cxt_nome;
    private javax.swing.JTextField cxt_saida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb_policial;
    // End of variables declaration//GEN-END:variables
}
