package view;

import controller.RefeicaoController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.RefeicaoModel;
import util.Relatorios;

/**
 *
 * @author felip
 */
public class RefeicaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PolicialPenalView
     */
    public RefeicaoView() {
        initComponents();
        inicializar();
        preencherTabela();
    }

    private int linha = -1; // USADO PARA VERIFICAR SE ALGUMA LINHA DA TABELA FOI SELECIONADA

    private void inicializar() {
        cxt_id.setEnabled(false);
        cxt_comida.setEnabled(false);
        cxt_diaSemana.setEnabled(false);
        cxt_horario.setEnabled(false);

        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
        btn_novo.setEnabled(true);

    }

    private void preencherTabela() {
        RefeicaoController controller = new RefeicaoController();
        ArrayList<RefeicaoModel> lista = controller.selecionarTodos();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NENHUMA  REFEIÇÃO CADASTRADA! (RefeicaoView ln 41)",
                    "Preenchendo tabela....", JOptionPane.INFORMATION_MESSAGE);

        } else {
            DefaultTableModel modeloTabela = (DefaultTableModel) tb_refeicao.getModel();
            modeloTabela.setRowCount(0);
            for (RefeicaoModel r : lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(r.getIdrefeicao()),
                    r.getComida(),
                    r.getDia_semana(),
                    r.getHorario()
                });
            }
        }
    }

    private void limparCampos() {
        cxt_id.setText("");
        cxt_comida.setText("");
        cxt_diaSemana.setText("");
        cxt_horario.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cxt_comida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cxt_diaSemana = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cxt_horario = new javax.swing.JTextField();
        cxt_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_refeicao = new javax.swing.JTable();
        btn_excluir = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Tela Refeição");

        jLabel1.setText("Comida:");

        cxt_comida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel3.setText("Dia da Semana:");

        cxt_diaSemana.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel4.setText("Horário:");

        cxt_horario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_idActionPerformed(evt);
            }
        });

        jLabel5.setText("Id:");

        tb_refeicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "COMIDA", "DIA", "HORÁRIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_refeicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_refeicaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_refeicao);
        if (tb_refeicao.getColumnModel().getColumnCount() > 0) {
            tb_refeicao.getColumnModel().getColumn(0).setResizable(false);
            tb_refeicao.getColumnModel().getColumn(1).setResizable(false);
            tb_refeicao.getColumnModel().getColumn(2).setResizable(false);
            tb_refeicao.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_excluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxt_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(94, 94, 94))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_diaSemana)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_imprimir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_fechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cxt_comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cxt_diaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cxt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_editar)
                    .addComponent(btn_novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_imprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxt_idActionPerformed

    }//GEN-LAST:event_cxt_idActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        RefeicaoModel refeicao = new RefeicaoModel();

        if (cxt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ESCOLHA UMA LINHA PARA EXCLUIR!", "Excluindo....",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {

            refeicao.setIdrefeicao(Integer.parseInt(cxt_id.getText()));

            // ---------------- CONTROLLER
            RefeicaoController controller = new RefeicaoController();
            if (controller.excluir(refeicao)) {
                JOptionPane.showMessageDialog(this, "Dados excluídos", "excluindo...!",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EXCLUIR CRIMES",
                        "Algo de errado não está certo....", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        cxt_id.setEnabled(false);
        cxt_comida.setEnabled(true);
        cxt_diaSemana.setEnabled(true);
        cxt_horario.setEnabled(true);

        btn_novo.setEnabled(false);
        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);

        limparCampos();
        cxt_comida.requestFocus();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        String comida = cxt_comida.getText();
        String dia = cxt_diaSemana.getText();
        String horario = cxt_horario.getText();

        if (comida.isEmpty() || dia.isEmpty() || horario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "INFORME TODOS OS CAMPOS!", "Atenção....", JOptionPane.WARNING_MESSAGE);

        } else {
            RefeicaoModel refeicao = new RefeicaoModel();
            refeicao.setComida(comida);
            refeicao.setDia_semana(dia);
            refeicao.setHorario(horario);

            // ------------ CONTROLLER
            RefeicaoController controller = new RefeicaoController();
            if (controller.inserir(refeicao)) {
                JOptionPane.showMessageDialog(this, "REFEIÇÃO CADASTRADS!", "Salvamento realizado...",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO INSERIR REFEIÇÃO", "Algo de errado não está certo....",
                        JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void acaoGerarRelatorio() throws IOException {
        Relatorios.relatorio("relatorio_refeicao", "", "");
    }

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        try {
            acaoGerarRelatorio();
        } catch (IOException ex) {
            Logger.getLogger(RefeicaoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void tb_refeicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_refeicaoMouseClicked
        linha = tb_refeicao.getSelectedRow();

        if (linha != -1) {
            cxt_id.setText(tb_refeicao.getValueAt(linha, 0).toString());
            cxt_comida.setText(tb_refeicao.getValueAt(linha, 1).toString());
            cxt_diaSemana.setText(tb_refeicao.getValueAt(linha, 2).toString());
            cxt_horario.setText(tb_refeicao.getValueAt(linha, 3).toString());

            btn_novo.setEnabled(false);
            btn_salvar.setEnabled(false);
            btn_editar.setEnabled(true);
            btn_excluir.setEnabled(true);

            cxt_id.setEnabled(false);
            cxt_comida.setEnabled(true);
            cxt_diaSemana.setEnabled(true);
            cxt_horario.setEnabled(true);
            linha = -1;

        }
    }//GEN-LAST:event_tb_refeicaoMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int id = Integer.parseInt(cxt_id.getText());
        String comida = cxt_comida.getText();
        String dia = cxt_diaSemana.getText();
        String horario = cxt_horario.getText();

        if (comida.isEmpty() || dia.isEmpty() || horario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe todos os campos.....", "Atenção!",
                    JOptionPane.WARNING_MESSAGE);

        } else {

            RefeicaoModel refeicao = new RefeicaoModel();
            refeicao.setIdrefeicao(id);
            refeicao.setComida(comida);
            refeicao.setDia_semana(dia);
            refeicao.setHorario(horario);

            // ---------------- CONTROLLER
            RefeicaoController controller = new RefeicaoController();
            if (controller.editar(refeicao)) {
                JOptionPane.showMessageDialog(this, "Dados Atualizados", "Atualizando...!",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EDITAR REFEICAO", "Algo de errado não está certo....",
                        JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_btn_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField cxt_comida;
    private javax.swing.JTextField cxt_diaSemana;
    private javax.swing.JTextField cxt_horario;
    private javax.swing.JTextField cxt_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb_refeicao;
    // End of variables declaration//GEN-END:variables
}
