/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Font;
import java.awt.Image;
import java.util.function.Supplier;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author felip
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        UIManager.put("InternalFrame.titleFont", new Font("Arial", Font.PLAIN, 20));

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/tropaDeElite2.jpg"));
        Image image = icon.getImage();
        panel_areaDeTrabalho = new javax.swing.JDesktopPane() {

            public void paintComponent(Graphics g) {
                g.drawImage(image, 0,0,getWidth(), getHeight(), this);
            }

        };
        menu_barra = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_ipl = new javax.swing.JMenuItem();
        menuItem_policialPenal = new javax.swing.JMenuItem();
        menuItem_celas = new javax.swing.JMenuItem();
        menuItem_crimes = new javax.swing.JMenuItem();
        menuItem_visitas = new javax.swing.JMenuItem();
        menuItem_refeicoes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel_areaDeTrabalhoLayout = new javax.swing.GroupLayout(panel_areaDeTrabalho);
        panel_areaDeTrabalho.setLayout(panel_areaDeTrabalhoLayout);
        panel_areaDeTrabalhoLayout.setHorizontalGroup(
            panel_areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );
        panel_areaDeTrabalhoLayout.setVerticalGroup(
            panel_areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N

        menuItem_ipl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItem_ipl.setText("Indivíduo Privado de Liberdade ");
        menuItem_ipl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_iplActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_ipl);

        menuItem_policialPenal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItem_policialPenal.setText("Políciais Penais");
        menuItem_policialPenal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_policialPenalActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_policialPenal);

        menuItem_celas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItem_celas.setText("Celas");
        menuItem_celas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_celasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_celas);

        menuItem_crimes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItem_crimes.setText("Crimes");
        menuItem_crimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_crimesActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_crimes);

        menuItem_visitas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItem_visitas.setText("Visitas");
        menuItem_visitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_visitasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_visitas);

        menuItem_refeicoes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuItem_refeicoes.setText("Refeições");
        menuItem_refeicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_refeicoesActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_refeicoes);

        menu_barra.add(jMenu1);
        menu_barra.add(jMenu2);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_areaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_areaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_celasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_celasActionPerformed
        abrirViewUnica(CelasView.class, CelasView::new);

    }//GEN-LAST:event_menuItem_celasActionPerformed

    private void menuItem_iplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_iplActionPerformed
        abrirViewUnica(IPLView.class, IPLView::new);
    }//GEN-LAST:event_menuItem_iplActionPerformed

    public JDesktopPane getPanel_areaDeTrabalho() {
        return panel_areaDeTrabalho;
    }

    public void setPanel_areaDeTrabalho(JDesktopPane panel_areaDeTrabalho) {
        this.panel_areaDeTrabalho = panel_areaDeTrabalho;
    }

    private void centralizarJInternalFrame(JInternalFrame frame) {

        int lDesk = getPanel_areaDeTrabalho().getWidth();
        int aDesk = getPanel_areaDeTrabalho().getHeight();

        int lFrame = frame.getWidth();
        int aFrame = frame.getHeight();

        frame.setLocation(lDesk / 2 - lFrame / 2, aDesk / 2 - aFrame / 2);
    }

    private void abrirViewUnica(Class<? extends JInternalFrame> classeView, Supplier<JInternalFrame> criadorView) {
        boolean jaAberta = false;

        for (JInternalFrame frame : panel_areaDeTrabalho.getAllFrames()) {
            if (classeView.isInstance(frame)) {
                jaAberta = true;

                try {
                    frame.setIcon(false); // Restaurar se minimizada
                    frame.setSelected(true); // Selecionar
                    frame.toFront(); // Trazer para frente
                } catch (java.beans.PropertyVetoException ex) {
                    ex.printStackTrace();
                }
                break;
            }
        }

        if (!jaAberta) {
            JInternalFrame novaView = criadorView.get();
            panel_areaDeTrabalho.add(novaView);
            novaView.setVisible(true);
            centralizarJInternalFrame(novaView);
        }
    }

    private void menuItem_policialPenalActionPerformed(java.awt.event.ActionEvent evt) {
        abrirViewUnica(PolicialPenalView.class, PolicialPenalView::new);
    }

    private void menuItem_refeicoesActionPerformed(java.awt.event.ActionEvent evt) {
        abrirViewUnica(RefeicaoView.class, RefeicaoView::new);
    }

    private void menuItem_crimesActionPerformed(java.awt.event.ActionEvent evt) {
        abrirViewUnica(CrimesView.class, CrimesView::new);
    }

    private void menuItem_visitasActionPerformed(java.awt.event.ActionEvent evt) {
        abrirViewUnica(VisitasView.class, VisitasView::new);
    }

    public void abreJanelaPesquisaDentroDeIPL() {
        abrirViewUnica(PesquisaView.class, PesquisaView::new);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem menuItem_celas;
    private javax.swing.JMenuItem menuItem_crimes;
    private javax.swing.JMenuItem menuItem_ipl;
    private javax.swing.JMenuItem menuItem_policialPenal;
    private javax.swing.JMenuItem menuItem_refeicoes;
    private javax.swing.JMenuItem menuItem_visitas;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JDesktopPane panel_areaDeTrabalho;
    // End of variables declaration//GEN-END:variables
}
