package view;

import controller.VisitasController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VisitasModel;
import util.Relatorios;

/**
 *
 * @author felip
 */
public class VisitasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PolicialPenalView
     */
    public VisitasView() {
        initComponents();
        inicializar();
        preencherTabela();
    }

    private int linha = -1;

    private void inicializar() {
        cxt_id.setEnabled(false);
        cxt_parentesco.setEnabled(false);
        cxt_data.setEnabled(false);
        cxt_presente.setEnabled(false);

        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(false);
        btn_novo.setEnabled(true);

    }

    private void preencherTabela() {
        VisitasController controller = new VisitasController();
        ArrayList<VisitasModel> lista = controller.selecionarTodos();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NENHUMA VISITA CADASTRADA! (VisitasView ln 41)",
                    "Preenchendo tabela....", JOptionPane.INFORMATION_MESSAGE);

        } else {
            DefaultTableModel modeloTabela = (DefaultTableModel) tb_visitas.getModel();
            modeloTabela.setRowCount(0);
            for (VisitasModel v : lista) {
                modeloTabela.addRow(new String[]{
                    String.valueOf(v.getIdvisitas()),
                    v.getParentesco(),
                    v.getData_visita(),
                    v.getPresente()
                });
            }
        }
    }

    private void limparCampos() {
        cxt_id.setText("");
        cxt_parentesco.setText("");
        cxt_data.setText("");
        cxt_presente.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cxt_parentesco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cxt_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_visitas = new javax.swing.JTable();
        btn_excluir = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();
        cxt_data = new javax.swing.JFormattedTextField();
        cxt_presente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Tela Visitas");

        jLabel1.setText("Parentesco:");

        cxt_parentesco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel3.setText("Data:");

        cxt_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cxt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxt_idActionPerformed(evt);
            }
        });

        jLabel5.setText("Id:");

        tb_visitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PARENTESCO", "DATA", "PRESENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_visitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_visitasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_visitas);
        if (tb_visitas.getColumnModel().getColumnCount() > 0) {
            tb_visitas.getColumnModel().getColumn(0).setResizable(false);
            tb_visitas.getColumnModel().getColumn(1).setResizable(false);
            tb_visitas.getColumnModel().getColumn(2).setResizable(false);
            tb_visitas.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_excluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_imprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        try {
            cxt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxt_data.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        cxt_presente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setText("Presente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_fechar))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_novo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_salvar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_data)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_imprimir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxt_presente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_fechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cxt_parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cxt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cxt_presente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_editar)
                    .addComponent(btn_novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_imprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxt_idActionPerformed

    }//GEN-LAST:event_cxt_idActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        VisitasModel visitas = new VisitasModel();

        if (cxt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ESCOLHA UMA LINHA PARA EXCLUIR!", "Excluindo....",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {

            visitas.setIdvisitas(Integer.parseInt(cxt_id.getText()));

            // ---------------- CONTROLLER
            VisitasController controller = new VisitasController();
            if (controller.excluir(visitas)) {
                JOptionPane.showMessageDialog(this, "Dados excluídos", "excluindo...!",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EXCLUIR VISITAS",
                        "Algo de errado não está certo....", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        cxt_id.setEnabled(false);
        cxt_parentesco.setEnabled(true);
        cxt_data.setEnabled(true);
        cxt_presente.setEnabled(true);

        btn_novo.setEnabled(false);
        btn_editar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_salvar.setEnabled(true);

        limparCampos();
        cxt_parentesco.requestFocus();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        String parentesco = cxt_parentesco.getText();
        String data = cxt_data.getText();
        String presente = cxt_presente.getText();

        if (parentesco.isEmpty() || data.isEmpty() || presente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "INFORME TODOS OS CAMPOS!", "Atenção....", JOptionPane.WARNING_MESSAGE);

        } else {
            VisitasModel visitas = new VisitasModel();
            visitas.setParentesco(parentesco);
            visitas.setData_visita(data);
            visitas.setPresente(presente);

            // ------------ CONTROLLER
            VisitasController controller = new VisitasController();
            if (controller.inserir(visitas)) {
                JOptionPane.showMessageDialog(this, "VISITA CADASTRADA!", "Salvamento realizado...",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO INSERIR VISITA", "Algo de errado não está certo....",
                        JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void acaoGerarRelatorio() throws IOException {
        Relatorios.relatorio("relatorio_visitas", "", "");
    }

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        try {
            acaoGerarRelatorio();
        } catch (IOException ex) {
            Logger.getLogger(VisitasView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int id = Integer.parseInt(cxt_id.getText());
        String parentesco = cxt_parentesco.getText();
        String data = cxt_data.getText();
        String presente = cxt_presente.getText();

        if (parentesco.isEmpty() || data.isEmpty() || presente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe todos os campos.....", "Atenção!",
                    JOptionPane.WARNING_MESSAGE);

        } else {

            VisitasModel visitas = new VisitasModel();
            visitas.setIdvisitas(id);
            visitas.setParentesco(parentesco);
            visitas.setData_visita(data);
            visitas.setPresente(presente);

            // ---------------- CONTROLLER
            VisitasController controller = new VisitasController();
            if (controller.editar(visitas)) {
                JOptionPane.showMessageDialog(this, "Dados Atualizados", "Atualizando...!",
                        JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                inicializar();
                preencherTabela();

            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EDITAR VISITAS", "Algo de errado não está certo....",
                        JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void tb_visitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_visitasMouseClicked
        linha = tb_visitas.getSelectedRow();

        if (linha != -1) {
            cxt_id.setText(tb_visitas.getValueAt(linha, 0).toString());
            cxt_parentesco.setText(tb_visitas.getValueAt(linha, 1).toString());
            cxt_data.setText(tb_visitas.getValueAt(linha, 2).toString());
            cxt_presente.setText(tb_visitas.getValueAt(linha, 3).toString());

            btn_novo.setEnabled(false);
            btn_salvar.setEnabled(false);
            btn_editar.setEnabled(true);
            btn_excluir.setEnabled(true);

            cxt_id.setEnabled(false);
            cxt_parentesco.setEnabled(true);
            cxt_data.setEnabled(true);
            cxt_presente.setEnabled(true);

            linha = -1;
        }
    }//GEN-LAST:event_tb_visitasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JFormattedTextField cxt_data;
    private javax.swing.JTextField cxt_id;
    private javax.swing.JTextField cxt_parentesco;
    private javax.swing.JTextField cxt_presente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb_visitas;
    // End of variables declaration//GEN-END:variables
}
